### ISSUE TITLE
Link to discussion of ch 9 replace is broken

### ISSUE THREAD

**Issue by ahelwer** [awalterschulze/the-little-typer-exercises#1]
I am also struggling with understanding replace but it appears the link to the google group discussion is broken in the README; is the group deleted? Archived anywhere? Thanks! P.S. I asked a question about the replace operator [here](https://cs.stackexchange.com/questions/154496/what-is-an-explanation-of-the-replace-operator-in-the-pie-language).

**Comment by awalterschulze** [comment]
It seems you need to be part of the google group to see the discussion.  I have made a pdf of the discussion for you, I hope this helps.

[Gmail - Session6 - 2019-02-19_ Summary.pdf](https://github.com/awalterschulze/the-little-typer-exercises/files/9706444/Gmail.-.Session6.-.2019-02-19_.Summary.pdf)

**Comment by ahelwer** [comment]
I ended up writing an extended dialogue explaining `replace` in a blog post: https://ahelwer.ca/post/2022-10-13-little-typer-ch9/

Thanks for uploading your discussions!

**Comment by awalterschulze** [comment]
That is a really great introduction.  Thank you so much for writing it up, I have now added it to the Readme and also made a tweet about it https://twitter.com/awalterschulze/status/1581241501966684160
